# Generated by Django 3.1.7 on 2021-03-03 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210304_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Укажите группу', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_posts', to='api.group', verbose_name='Группа'),
        ),
    ]
